### ISSUE TITLE
مشکل در لینک سابسکریپشن

### ISSUE THREAD

**Issue by radin-mg** [MatinDehghanian/MarzViteTemplate#6]
سلام وقت بخیر
متشکرم از توسعه این تمپلیت، واقعا عالیه 🤩
فقط من به یه مشکل بر خوردم، در قسمت افزودن سابسکریپشن، دامین آدرس ساب دو بار تکرار میشه و این باعث میشه توی اپ سابسکریپشن کار نکنه

![photo_2024-10-16_17-34-55](https://github.com/user-attachments/assets/413914e8-45b5-4ad6-8220-75d37712ce7c)

**Comment by MatinDehghanian** [comment]
سلام امیدوارم حالت خوب باشه
ممنون از issue
با کامیت https://github.com/MatinDehghanian/sub-vite/commit/cdd2f5673769ce5347c9f916c4fc4dcffae9e42e
این مشکل حل شد
بیلد نگرفته بودم بعدش که اون هم یک ساعت پیش آپدیت شد
مجدد تست کن بی زحمت

**Comment by radin-mg** [comment]
ممنونم، همچنین
مجددا تست کردم، همچنان این مشکل هست

**Comment by MatinDehghanian** [comment]
ارادت
طبق کامیت https://github.com/MatinDehghanian/sub-vite/commit/9b85f3060f79032f2bd16995ad296d0f836862ff
مشکل احتمالا رفع شده
مجدد ریلیز ها آپدیت شدن
تست کنید

**Comment by radin-mg** [comment]
متشکرم، لطف کردین
حل شد

**Comment by MatinDehghanian** [comment]
Solved

**Comment by BYP455** [comment]
سلام و وقت بخیر
اول تشکر میکنم
چرا پروژه ناقص اپلود شده... قسمت apps & infocards & icons... داخل سورس نیست
