### ISSUE TITLE
[Solved]

### ISSUE THREAD

**Issue by BYP455** [MatinDehghanian/MarzViteTemplate#7]

**Comment by MatinDehghanian** [comment]
<img width="1156" alt="image" src="https://github.com/user-attachments/assets/9e644a64-86c7-4706-ac0a-a7284f43b676">

**Comment by MatinDehghanian** [comment]
https://github.com/MatinDehghanian/MarzViteTemplate/blob/main/src/components/ClientTab/ServiceComponents/InfoCard.jsx

**Comment by MatinDehghanian** [comment]
لطفا index.html رو پاک کنید و مجددا تلاش کنید
احتمالا توی فرآیند قسمتی رو اشتباه رفتید
الان روی مرزبان تست کردم و موردی نداشت

**Comment by BYP455** [comment]
تشکر متین جان
چند مرحله سعی کردم

اسکرین گرفتم ... ممنون میشم یک راهنمایی کنی 

https://github.com/user-attachments/assets/76226795-d260-44e1-9a95-1ec7b180815d

**Comment by MatinDehghanian** [comment]
لطفا توی تلگرام به ایدی @Mqtin پیام بده
تا دیباگ کنیم باهم
